[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
branch = true
source = ["jwt"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
atomic = true
combine_as_imports = true
line_length = 79
