---
name: CI

on:
  - push
  - pull_request

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }} (${{ matrix.crypto }})
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        crypto:
          - crypto
          - nocrypto

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python -m pip install tox coverage[toml]

      - name: Run tests
        run: python -m tox -e py-${{ matrix.crypto }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
